name: php7-pecl-apcu
profiles:
  php70w:
    define:
      basepkg: php70w
  php71w:
    define:
      basepkg: php71w
builds:
  webtatic-el7:
    target: el7-development
    arch: [x86_64]
    profiles:
      - php70w
      - php71w
  webtatic-el6:
    target: el6-development
    arch: [x86_64, i386]
    profiles:
      - php70w
      - php71w
